import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — Argus',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#080808] text-white">
      <div className="max-w-[680px] mx-auto px-6 py-24">
        <Link href="/" className="text-[#FA4500] text-sm hover:underline mb-8 inline-block">&larr; Back to home</Link>
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-12">Last updated: February 22, 2026</p>

        <div className="space-y-8 text-[15px] leading-[1.8] text-white/60">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Argus (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
            <p>Argus is an AI-powered website cloning tool that scrapes publicly accessible websites, extracts design systems, and rebuilds them in sandboxed environments. The generated code is provided as-is for learning, prototyping, and development purposes.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. User Responsibilities</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>You must be at least 13 years old to use the Service.</li>
              <li>You are responsible for all activity under your account.</li>
              <li>You must not use Argus to clone websites in violation of copyright, trademark, or other intellectual property rights.</li>
              <li>You must not use the Service for illegal, harmful, or abusive purposes.</li>
              <li>You must not attempt to circumvent rate limits, access controls, or security measures.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Intellectual Property</h2>
            <p>You own the code generated by Argus for your use. However, Argus does not grant you rights to the original website&apos;s content, branding, or intellectual property. You are responsible for ensuring your use of generated code complies with applicable laws.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Pricing and Billing</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Free tier: 30 credits per month, no credit card required.</li>
              <li>Pro tier: $19/month for 300 credits, billed monthly.</li>
              <li>You can cancel your subscription at any time. Cancellation takes effect at the end of the current billing period.</li>
              <li>Refunds are handled on a case-by-case basis.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Limitation of Liability</h2>
            <p>Argus is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to loss of data, revenue, or business opportunities. Our total liability is limited to the amount you paid in the last 12 months.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Termination</h2>
            <p>We reserve the right to suspend or terminate your account at any time for violation of these terms, abuse of the Service, or any other reason at our sole discretion.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Changes to Terms</h2>
            <p>We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the revised terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Contact</h2>
            <p>Questions about these terms? Email us at <a href="mailto:hello@argus.build" className="text-[#FA4500] hover:underline">hello@argus.build</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
